--CRIAÇÃO USUARIO PARA ACESSAR BANCO
CREATE LOGIN AlunoFS13
WITH PASSWORD = '1234';

--ATRIBUINDO O PERFIL DO LOGIN ALUNO PARA O USUARIO
CREATE USER AlunoFS13 FOR LOGIN AlunoFS13;

--ATRIBUINDO PERMISSAO APENAS PARA SELECT NESSE USUARIO
GRANT SELECT TO AlunoFS13;

